import type { Request, Response, NextFunction } from 'express';
import { db } from '../db';
import { twoFactorService, EMAIL_OTP_MAX_ATTEMPTS, type PendingEmailOtp } from '../services/twoFactor.service';
import { appConfigService } from '../services/appConfig.service';
import { authService } from '../services/auth.service';
import { tenantService } from '../services/tenant.service';
import { AppError } from '../middleware/errorHandler';
import { logger } from '../utils/logger';
import { auditService } from '../services/audit.service';
import { comparePassword } from '../utils/crypto';
import { regenerateSession } from '../utils/regenerateSession';

// Extend session type for 2FA state
declare module 'express-session' {
  interface SessionData {
    pendingMfaUserId?: number;
    pendingMfaLinkToken?: string;
    pendingTotpSecret?: string;
    pendingTotpExpiresAt?: number;
    /** The pending setup replaces a live TOTP (its proof was a code of it). */
    pendingTotpReplaces?: boolean;
    pendingEmailOtp?: PendingEmailOtp;
    pendingEmailOtpSetup?: PendingEmailOtp;
  }
}

/** Lifetime of a TOTP secret generated by /totp/setup and not yet enabled. */
const PENDING_TOTP_TTL_MS = 10 * 60 * 1000;

type ProofOutcome = { ok: true } | { ok: false; status: number; body: Record<string, unknown> };

/**
 * Proof for adding, replacing or removing a second factor (SECURITY-PARITY-8):
 *   - the account has a TOTP: a CURRENT code of it (body.currentCode), claimed
 *     against the anti-replay step (the sign-in code itself is refused);
 *   - otherwise (e-mail codes only, or no factor yet): the CURRENT PASSWORD
 *     (body.currentPassword).
 * A stolen session cookie alone can neither plant a factor the attacker
 * controls nor remove the user's. Wrong proofs set
 * res.locals.currentPasswordRejected, which the per-account
 * currentPasswordLimiter mounted on these routes counts (5 / 15 min).
 * Failures answer 400 (never 401: the client treats 401 as a dead session).
 */
async function checkFactorProof(req: Request, res: Response): Promise<ProofOutcome> {
  const userId = req.session.userId!;
  const row = await db('users').where({ id: userId })
    .first('totp_enabled', 'totp_secret', 'password_hash', 'foreign_source') as {
      totp_enabled: boolean | null; totp_secret: string | null; password_hash: string | null; foreign_source: string | null;
    } | undefined;
  if (!row) return { ok: false, status: 401, body: { success: false, error: 'User not found' } };
  const body = (req.body ?? {}) as { currentCode?: unknown; currentPassword?: unknown };

  if (row.totp_enabled && row.totp_secret) {
    const code = typeof body.currentCode === 'string' || typeof body.currentCode === 'number' ? String(body.currentCode).trim() : '';
    if (!code) {
      return { ok: false, status: 400, body: { success: false, error: 'Current authenticator code required', proofRequired: 'totp' } };
    }
    const secret = twoFactorService.openTotpSecret(row.totp_secret);
    const step = secret ? twoFactorService.verifyTotpStep(secret, code) : null;
    if (step === null || !(await twoFactorService.acceptTotpStep(userId, step))) {
      res.locals.currentPasswordRejected = true;
      await auditService.logReq(req, { action: 'profile.factor_proof', targetType: 'user', targetId: userId, success: false, details: { proof: 'totp' } });
      return { ok: false, status: 400, body: { success: false, error: 'Invalid code', proofRequired: 'totp', proofInvalid: true } };
    }
    return { ok: true };
  }

  // Obligate accounts have no usable local password (they sign in through
  // Obligate only): their factors are managed there.
  if (row.foreign_source === 'obligate') {
    return { ok: false, status: 403, body: { success: false, error: 'The second factors of an Obligate account are managed in Obligate' } };
  }
  const password = typeof body.currentPassword === 'string' ? body.currentPassword : '';
  if (!password) {
    return { ok: false, status: 400, body: { success: false, error: 'Current password required', proofRequired: 'password' } };
  }
  if (!row.password_hash || !(await comparePassword(password, row.password_hash))) {
    res.locals.currentPasswordRejected = true;
    await auditService.logReq(req, { action: 'profile.factor_proof', targetType: 'user', targetId: userId, success: false, details: { proof: 'password' } });
    return { ok: false, status: 400, body: { success: false, error: 'Invalid password', proofRequired: 'password', proofInvalid: true } };
  }
  return { ok: true };
}

/** Notice to the account's address when a second factor is added, replaced
 *  or removed (best effort, only if the OTP SMTP server is set). */
function notifyFactorChange(userId: number, subject: string, lines: string[]): void {
  void (async () => {
    try {
      const row = await db('users').where({ id: userId }).first('email') as { email: string | null } | undefined;
      if (!row?.email) return;
      const cfg = await appConfigService.getAll();
      if (!cfg.otp_smtp_server_id) return;
      await twoFactorService.sendSecurityNotice(Number(cfg.otp_smtp_server_id), row.email, subject, lines);
    } catch (err) {
      logger.warn({ err, userId }, 'Second-factor change notice not sent');
    }
  })();
}

const NOT_YOU = 'If this was not you, change your password now and ask an administrator to reset your two-factor authentication.';

function clearPendingTotp(req: Request): void {
  delete req.session.pendingTotpSecret;
  delete req.session.pendingTotpExpiresAt;
  delete req.session.pendingTotpReplaces;
}

/**
 * Checks a typed code against a pending e-mail code kept in the session.
 * A wrong code counts against the pending code; after EMAIL_OTP_MAX_ATTEMPTS
 * wrong codes it is dropped (a new code must be requested).
 */
function consumeEmailOtp(req: Request, key: 'pendingEmailOtp' | 'pendingEmailOtpSetup', code: unknown): boolean {
  const pending = req.session[key];
  if (!pending) return false;
  if (twoFactorService.emailOtpMatches(pending, code)) return true;
  const attempts = (pending.attempts ?? 0) + 1;
  if (attempts >= EMAIL_OTP_MAX_ATTEMPTS || Date.now() > pending.expires) delete req.session[key];
  else req.session[key] = { ...pending, attempts };
  return false;
}

export const twoFactorController = {
  // ── Profile endpoints (authenticated) ─────────────────────────────────────

  async status(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const user = await authService.getUserById(req.session.userId!);
      if (!user) throw new AppError(401, 'User not found');
      res.json({ success: true, data: {
        totpEnabled: user.totpEnabled ?? false,
        emailOtpEnabled: user.emailOtpEnabled ?? false,
        email: user.email ?? null,
      }});
    } catch (err) { next(err); }
  },

  // TOTP setup step 1: generate secret + QR (stored in session, 10 min).
  // When the account already has a factor (TOTP or e-mail codes), a proof is
  // required first (current TOTP code, else the current password). A first
  // enrolment (no factor at all, e.g. the enrollment wizard) needs none.
  async totpSetup(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const row = await db('users').where({ id: req.session.userId! })
        .first('username', 'totp_enabled', 'totp_secret', 'email_otp_enabled') as {
          username: string; totp_enabled: boolean | null; totp_secret: string | null; email_otp_enabled: boolean | null;
        } | undefined;
      if (!row) throw new AppError(401, 'User not found');
      const hasTotp = !!(row.totp_enabled && row.totp_secret);
      if (hasTotp || row.email_otp_enabled) {
        const proof = await checkFactorProof(req, res);
        if (!proof.ok) { res.status(proof.status).json(proof.body); return; }
      }
      const { secret, uri } = twoFactorService.generateTotpSecret(row.username);
      const qrDataUrl = await twoFactorService.generateTotpQr(uri);
      // Bounded: a forgotten enrolment must not leave a usable secret in the
      // session store indefinitely.
      req.session.pendingTotpSecret = secret;
      req.session.pendingTotpExpiresAt = Date.now() + PENDING_TOTP_TTL_MS;
      req.session.pendingTotpReplaces = hasTotp;
      res.json({ success: true, data: { secret, qrDataUrl } });
    } catch (err) { next(err); }
  },

  // TOTP setup step 2: verify code, save the (encrypted) secret and enable
  async totpEnable(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const { code } = req.body ?? {};
      const userId = req.session.userId!;
      const secret = req.session.pendingTotpSecret;
      if (!secret) throw new AppError(400, 'No pending TOTP setup. Call /setup first.');
      if (Date.now() > (req.session.pendingTotpExpiresAt ?? 0)) {
        clearPendingTotp(req);
        throw new AppError(400, 'TOTP setup expired. Call /setup again.');
      }
      const step = twoFactorService.verifyTotpStep(secret, String(code ?? ''));
      if (step === null) throw new AppError(400, 'Invalid code');

      // One conditional UPDATE:
      //   - anti-replay: the step must be newer than the last accepted one, and
      //     it is recorded (the enabling code can never sign in later);
      //   - a setup started while no TOTP was live (no TOTP proof given) must
      //     not overwrite a TOTP enabled in the meantime from another session.
      const replaces = !!req.session.pendingTotpReplaces;
      const upd = db('users').where({ id: userId })
        .where((q) => q.whereNull('totp_last_step').orWhere('totp_last_step', '<', step));
      if (!replaces) {
        upd.where((q) => q.where('totp_enabled', false).orWhereNull('totp_enabled').orWhereNull('totp_secret'));
      }
      const updated = await upd.update({
        totp_secret: twoFactorService.sealTotpSecret(secret),
        totp_enabled: true,
        totp_last_step: step,
      });
      if (!updated) {
        const cur = await db('users').where({ id: userId }).first('totp_last_step') as { totp_last_step: string | number | null } | undefined;
        if (cur?.totp_last_step != null && Number(cur.totp_last_step) >= step) {
          // Same 30 s step as a code already accepted (e.g. the proof): the
          // pending setup is kept, the next code works.
          throw new AppError(400, 'This code was already used. Wait for the next code.');
        }
        clearPendingTotp(req);
        throw new AppError(409, 'Two-factor authentication was enabled in the meantime. Start the setup again.');
      }
      clearPendingTotp(req);
      await auditService.logReq(req, { action: 'profile.totp_enabled', targetType: 'user', targetId: userId, details: { replaced: replaces } });
      notifyFactorChange(userId, replaces ? 'Authenticator app replaced' : 'Authenticator app added', [
        replaces
          ? 'The authenticator app (TOTP) used for two-factor authentication on your account was replaced.'
          : 'An authenticator app (TOTP) was added for two-factor authentication on your account.',
        NOT_YOU,
      ]);
      res.json({ success: true });
    } catch (err) { next(err); }
  },

  async totpDisable(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const userId = req.session.userId!;
      const row = await db('users').where({ id: userId }).first('totp_enabled', 'totp_secret') as
        { totp_enabled: boolean | null; totp_secret: string | null } | undefined;
      const hadTotp = !!(row?.totp_enabled && row?.totp_secret);
      // Removing a live TOTP needs a current code of it.
      if (hadTotp) {
        const proof = await checkFactorProof(req, res);
        if (!proof.ok) { res.status(proof.status).json(proof.body); return; }
      }
      // totp_last_step is kept: a re-enabled TOTP still refuses old steps.
      await db('users').where({ id: userId }).update({
        totp_secret: null,
        totp_enabled: false,
      });
      clearPendingTotp(req);
      if (hadTotp) {
        await auditService.logReq(req, { action: 'profile.totp_disabled', targetType: 'user', targetId: userId });
        notifyFactorChange(userId, 'Authenticator app removed', [
          'The authenticator app (TOTP) was removed from your account: two-factor authentication by authenticator app is off.',
          NOT_YOU,
        ]);
      }
      res.json({ success: true });
    } catch (err) { next(err); }
  },

  // Email OTP setup step 1: send a code to the account's PROFILE address.
  //
  // This route never changes users.email (an address change goes through
  // PUT /profile and its current-password check), so it can neither bypass
  // that check nor move the password-reset channel. Enabling e-mail codes adds
  // a sign-in factor: the factor proof is required before any code is sent.
  async emailSetup(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const row = await db('users').where({ id: req.session.userId! }).first('email') as { email: string | null } | undefined;
      const profileEmail = String(row?.email ?? '').trim();
      if (!profileEmail) throw new AppError(400, 'Set an e-mail address in your profile first.');
      const asked = typeof req.body?.email === 'string' ? req.body.email.trim() : '';
      if (asked && asked.toLowerCase() !== profileEmail.toLowerCase()) {
        throw new AppError(400, 'Codes are sent to the e-mail address of your profile. Change it in your profile first.');
      }
      const cfg = await appConfigService.getAll();
      if (!cfg.otp_smtp_server_id) throw new AppError(400, 'No SMTP server configured for OTP. Ask your administrator.');
      const proof = await checkFactorProof(req, res);
      if (!proof.ok) { res.status(proof.status).json(proof.body); return; }
      const { code, pending } = twoFactorService.newEmailOtp(profileEmail);
      req.session.pendingEmailOtpSetup = pending;
      await twoFactorService.sendEmailOtp(Number(cfg.otp_smtp_server_id), profileEmail, code);
      res.json({ success: true, message: `Code sent to ${profileEmail}`, data: { email: profileEmail } });
    } catch (err) { next(err); }
  },

  // Email OTP setup step 2: verify the mailed code and enable e-mail codes
  // (on the profile address, which is NOT written here).
  async emailEnable(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const { code } = req.body ?? {};
      const pending = req.session.pendingEmailOtpSetup;
      if (!pending) throw new AppError(400, 'No pending email OTP setup. Call /setup first.');
      if (Date.now() > pending.expires) {
        delete req.session.pendingEmailOtpSetup;
        throw new AppError(400, 'Code expired');
      }
      if (!consumeEmailOtp(req, 'pendingEmailOtpSetup', code)) throw new AppError(400, 'Invalid code');
      delete req.session.pendingEmailOtpSetup;
      // Only if the profile address is still the one the code went to.
      const updated = await db('users')
        .where({ id: req.session.userId })
        .whereRaw('lower(trim(email)) = ?', [pending.email.trim().toLowerCase()])
        .update({ email_otp_enabled: true });
      if (!updated) throw new AppError(409, 'Your e-mail address changed during the setup. Start again.');
      await auditService.logReq(req, { action: 'profile.email_otp_enabled', targetType: 'user', targetId: req.session.userId! });
      notifyFactorChange(req.session.userId!, 'E-mail codes enabled', [
        'Sign-in codes by e-mail were enabled on your account, sent to this address.',
        NOT_YOU,
      ]);
      res.json({ success: true });
    } catch (err) { next(err); }
  },

  async emailDisable(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const userId = req.session.userId!;
      const row = await db('users').where({ id: userId }).first('email_otp_enabled') as { email_otp_enabled: boolean | null } | undefined;
      // Removing a sign-in factor needs the same proof as adding one.
      if (row?.email_otp_enabled) {
        const proof = await checkFactorProof(req, res);
        if (!proof.ok) { res.status(proof.status).json(proof.body); return; }
      }
      await db('users').where({ id: userId }).update({ email_otp_enabled: false });
      delete req.session.pendingEmailOtpSetup;
      if (row?.email_otp_enabled) {
        await auditService.logReq(req, { action: 'profile.email_otp_disabled', targetType: 'user', targetId: userId });
        notifyFactorChange(userId, 'E-mail codes disabled', [
          'Sign-in codes by e-mail were disabled on your account.',
          NOT_YOU,
        ]);
      }
      res.json({ success: true });
    } catch (err) { next(err); }
  },

  // ── Auth endpoints (after step-1 login, session has pendingMfaUserId) ─────

  async verify(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const { code, method } = req.body ?? {};
      const userId = req.session.pendingMfaUserId;
      if (!userId) throw new AppError(400, 'No pending 2FA session');

      const row = await db('users')
        .where({ id: userId, is_active: true })
        .first('id', 'username', 'role', 'totp_secret', 'totp_enabled', 'email_otp_enabled', 'email');

      if (!row) {
        // Deleted or disabled while the 2FA step was pending: same answer as an
        // expired pending session (does not reveal the disabled state).
        delete req.session.pendingMfaUserId;
        delete req.session.pendingEmailOtp;
        throw new AppError(400, 'No pending 2FA session');
      }

      let valid = false;

      if (method === 'totp' && row.totp_enabled && row.totp_secret) {
        const secret = twoFactorService.openTotpSecret(row.totp_secret);
        const step = secret ? twoFactorService.verifyTotpStep(secret, String(code ?? '')) : null;
        // Anti-replay: the step is claimed atomically; a code already used
        // (by this or any other pending session) is refused.
        valid = step !== null && await twoFactorService.acceptTotpStep(row.id, step);
        // Legacy plaintext secret: sealed now that it is known to be good.
        if (valid && secret && !twoFactorService.isSealedTotpSecret(row.totp_secret)) {
          await db('users').where({ id: row.id, totp_secret: row.totp_secret })
            .update({ totp_secret: twoFactorService.sealTotpSecret(secret) })
            .catch((err) => logger.warn({ err, userId: row.id }, 'TOTP secret re-encryption failed'));
        }
      } else if (method === 'totp') {
        logger.warn({ userId, totpEnabled: row.totp_enabled, hasSecret: !!row.totp_secret },
          'TOTP verify: totp_enabled or totp_secret missing in DB');
      } else if (method === 'email' && row.email_otp_enabled) {
        valid = consumeEmailOtp(req, 'pendingEmailOtp', code);
      }

      if (!valid) {
        await auditService.logReq(req, {
          action: 'auth.login', tenantId: null, userId: row.id, username: row.username,
          targetType: 'user', targetId: row.id, success: false,
          details: { method: method === 'email' ? 'email' : 'totp', reason: 'invalid_second_factor' },
        });
        throw new AppError(401, 'Invalid code');
      }

      // Complete the session on a FRESH session id (anti session-fixation);
      // regenerate() also drops pendingMfaUserId / pendingEmailOtp.
      await regenerateSession(req);
      req.session.userId = row.id;
      req.session.username = row.username;
      req.session.role = row.role;

      // Landing tenant (favourite, else first membership, else Default for
      // platform admins only); the session was just regenerated, so no tenant
      // is left over when none resolves.
      const tenantId = await tenantService.resolveLoginTenant(row.id, row.role);
      if (tenantId !== null) req.session.currentTenantId = tenantId;
      await auditService.logReq(req, {
        action: 'auth.login', targetType: 'user', targetId: row.id,
        details: { method: method === 'email' ? 'email' : 'totp' },
      });

      const user = await authService.getUserById(row.id);
      res.json({ success: true, data: { user } });
    } catch (err) { next(err); }
  },

  async resendEmail(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const userId = req.session.pendingMfaUserId;
      if (!userId) throw new AppError(400, 'No pending 2FA session');

      const row = await db('users').where({ id: userId }).first('email', 'email_otp_enabled');
      if (!row || !row.email_otp_enabled || !row.email) {
        throw new AppError(400, 'Email OTP not configured for this user');
      }

      const cfg = await appConfigService.getAll();
      if (!cfg.otp_smtp_server_id) throw new AppError(400, 'No SMTP server configured for OTP');

      const { code, pending } = twoFactorService.newEmailOtp(row.email);
      req.session.pendingEmailOtp = pending;
      await twoFactorService.sendEmailOtp(Number(cfg.otp_smtp_server_id), row.email, code);
      res.json({ success: true, message: `Code sent to ${row.email}` });
    } catch (err) { next(err); }
  },
};
