//go:build linux

package main

import (
	"fmt"
	"os"
	"strings"
)

// readMachineUUID returns a stable per-instance UUID for this Linux machine.
//
// Priority:
//  1. /etc/machine-id — generated by systemd on first boot, world-readable,
//     unique per OS install, and regenerated after VM cloning when
//     systemd-machine-id-setup is used. Best choice for mixed bare-metal/VM
//     environments because it identifies an OS instance, not the hardware.
//  2. /sys/class/dmi/id/product_uuid — SMBIOS UUID, hardware-level, identical
//     to what Windows reads via Win32_ComputerSystemProduct. Requires root on
//     some distros (Ubuntu restricts it), and is shared across cloned VMs that
//     haven't had their SMBIOS reset. Used only when machine-id is absent.
//
// Returns "" if no stable ID can be found.
func readMachineUUID() string {
	// Primary: systemd machine-id (32 hex chars, no dashes).
	// Formatted as a standard UUID so the value is consistent with other platforms.
	for _, path := range []string{"/etc/machine-id", "/var/lib/dbus/machine-id"} {
		if b, err := os.ReadFile(path); err == nil {
			id := strings.TrimSpace(string(b))
			if len(id) == 32 {
				uuid := fmt.Sprintf("%s-%s-%s-%s-%s",
					id[0:8], id[8:12], id[12:16], id[16:20], id[20:32])
				if u := normaliseUUID(uuid); u != "" {
					return u
				}
			}
		}
	}

	// Fallback: SMBIOS product UUID (requires root on some distros,
	// shared across cloned VMs without SMBIOS reset).
	for _, path := range []string{
		"/sys/class/dmi/id/product_uuid",
		"/sys/devices/virtual/dmi/id/product_uuid",
	} {
		if b, err := os.ReadFile(path); err == nil {
			if uuid := normaliseUUID(strings.TrimSpace(string(b))); uuid != "" {
				return uuid
			}
		}
	}

	return ""
}
